export const colorsGoal = [
  {color: '#d32f2e'},
  {color: '#c2175b'},
  {color: '#7a1fa2'},
  {color: '#512da7'},
  {color: '#303e9f'},
  {color: '#0288d1'},
  {color: '#0098a6'},
  {color: '#00796a'},
  {color: '#398e3d'},
  {color: '#689f39'},
  {color: '#b0b42b'},
  {color: '#fac02e'},
  {color: '#ff9f00'},
  {color: '#f67c01'},
  {color: '#e64a19'},
  {color: '#5d4038'},
  {color: '#465a65'},
  {color: '#616161'},
];

// Material Comunity Icons
export const iconGoal = {
  Todos: [
    {id: 1, iconName: 'heart'},
    {id: 2, iconName: 'heart-multiple'},
    {id: 3, iconName: 'account-heart'},
    {id: 4, iconName: 'heart-circle'},
    {id: 5, iconName: 'home-heart'},
    {id: 6, iconName: 'heart-pulse'},
    {id: 7, iconName: 'tag-heart'},
    {id: 8, iconName: 'calendar-heart'},
    {id: 9, iconName: 'bike'},
    {id: 10, iconName: 'car-hatchback'},
    {id: 11, iconName: 'car-convertible'},
    {id: 12, iconName: 'motorbike'},
    {id: 13, iconName: 'airplane'},
    {id: 14, iconName: 'bus-side'},
    {id: 15, iconName: 'airballoon'},
    {id: 16, iconName: 'rocket'},
    {id: 17, iconName: 'cow'},
    {id: 18, iconName: 'dog'},
    {id: 19, iconName: 'paw'},
    {id: 20, iconName: 'bat'},
    {id: 21, iconName: 'cat'},
    {id: 22, iconName: 'duck'},
    {id: 23, iconName: 'sheep'},
    {id: 24, iconName: 'elephant'},
    {id: 25, iconName: 'emoticon'},
    {id: 26, iconName: 'emoticon-angry'},
    {id: 27, iconName: 'emoticon-cool'},
    {id: 28, iconName: 'emoticon-cry'},
    {id: 29, iconName: 'emoticon-kiss'},
    {id: 30, iconName: 'emoticon-wink'},
    {id: 31, iconName: 'cake-variant'},
    {id: 32, iconName: 'taco'},
    {id: 33, iconName: 'mushroom-outline'},
    {id: 34, iconName: 'muffin'},
    {id: 35, iconName: 'ice-cream'},
    {id: 36, iconName: 'food-fork-drink'},
    {id: 37, iconName: 'christianity-outline'},
    {id: 38, iconName: 'church'},
    {id: 39, iconName: 'charity'},
    {id: 40, iconName: 'christianity'},
    {id: 41, iconName: 'boombox'},
    {id: 42, iconName: 'music-note'},
    {id: 43, iconName: 'guitar-acoustic'},
    {id: 44, iconName: 'guitar-electric'},
    {id: 45, iconName: 'music'},
    {id: 46, iconName: 'brightness-5'},
    {id: 47, iconName: 'flare'},
    {id: 48, iconName: 'sprout-outline'},
    {id: 49, iconName: 'flower'},
    {id: 50, iconName: 'flower-poppy'},
    {id: 51, iconName: 'flower-tulip'},
    {id: 52, iconName: 'cactus'},
    {id: 53, iconName: 'anchor'},
    {id: 54, iconName: 'alarm-light'},
    {id: 55, iconName: 'calculator'},
    {id: 56, iconName: 'compass-outline'},
    {id: 57, iconName: 'crown'},
    {id: 58, iconName: 'desktop-mac'},
    {id: 59, iconName: 'gamepad-variant'},
    {id: 60, iconName: 'notebook'},
    {id: 61, iconName: 'palette'},
    {id: 62, iconName: 'telescope'},
    {id: 63, iconName: 'tshirt-crew-outline'},
    {id: 64, iconName: 'shoe-heel'},
    {id: 65, iconName: 'tshirt-v'},
    {id: 66, iconName: 'shoe-formal'},
    {id: 67, iconName: 'ring'},
    {id: 68, iconName: 'city'},
    {id: 69, iconName: 'home-group'},
    {id: 70, iconName: 'home-city'},
    {id: 71, iconName: 'home-modern'},
    {id: 72, iconName: 'shield-cross'},
  ],
  Amor: [
    {id: 1, iconName: 'heart'},
    {id: 2, iconName: 'heart-multiple'},
    {id: 3, iconName: 'account-heart'},
    {id: 4, iconName: 'heart-circle'},
    {id: 5, iconName: 'home-heart'},
    {id: 6, iconName: 'heart-pulse'},
    {id: 7, iconName: 'tag-heart'},
    {id: 8, iconName: 'calendar-heart'},
  ],
  Automotivos: [
    {id: 9, iconName: 'bike'},
    {id: 10, iconName: 'car-hatchback'},
    {id: 11, iconName: 'car-convertible'},
    {id: 12, iconName: 'motorbike'},
    {id: 13, iconName: 'airplane'},
    {id: 14, iconName: 'bus-side'},
    {id: 15, iconName: 'airballoon'},
    {id: 16, iconName: 'rocket'},
  ],
  Animais: [
    {id: 17, iconName: 'cow'},
    {id: 18, iconName: 'dog'},
    {id: 19, iconName: 'paw'},
    {id: 20, iconName: 'bat'},
    {id: 21, iconName: 'cat'},
    {id: 22, iconName: 'duck'},
    {id: 23, iconName: 'sheep'},
    {id: 24, iconName: 'elephant'},
  ],
  Carinhas: [
    {id: 25, iconName: 'emoticon'},
    {id: 26, iconName: 'emoticon-angry'},
    {id: 27, iconName: 'emoticon-cool'},
    {id: 28, iconName: 'emoticon-cry'},
    {id: 29, iconName: 'emoticon-kiss'},
    {id: 30, iconName: 'emoticon-wink'},
  ],
  Comidas: [
    {id: 31, iconName: 'cake-variant'},
    {id: 32, iconName: 'taco'},
    {id: 33, iconName: 'mushroom-outline'},
    {id: 34, iconName: 'muffin'},
    {id: 35, iconName: 'ice-cream'},
    {id: 36, iconName: 'food-fork-drink'},
  ],
  Espiritualidade: [
    {id: 37, iconName: 'christianity-outline'},
    {id: 38, iconName: 'church'},
    {id: 39, iconName: 'charity'},
    {id: 40, iconName: 'christianity'},
    {id: 72, iconName: 'shield-cross'},
  ],
  Som: [
    {id: 41, iconName: 'boombox'},
    {id: 42, iconName: 'music-note'},
    {id: 43, iconName: 'guitar-acoustic'},
    {id: 44, iconName: 'guitar-electric'},
    {id: 45, iconName: 'music'},
  ],
  Natureza: [
    {id: 46, iconName: 'brightness-5'},
    {id: 47, iconName: 'flare'},
    {id: 48, iconName: 'sprout-outline'},
    {id: 49, iconName: 'flower'},
    {id: 50, iconName: 'flower-poppy'},
    {id: 51, iconName: 'flower-tulip'},
    {id: 52, iconName: 'cactus'},
  ],
  Objetos: [
    {id: 53, iconName: 'anchor'},
    {id: 54, iconName: 'alarm-light'},
    {id: 55, iconName: 'calculator'},
    {id: 56, iconName: 'compass-outline'},
    {id: 57, iconName: 'crown'},
    {id: 58, iconName: 'desktop-mac'},
    {id: 59, iconName: 'gamepad-variant'},
    {id: 60, iconName: 'notebook'},
    {id: 61, iconName: 'palette'},
    {id: 62, iconName: 'telescope'},
  ],
  Roupas: [
    {id: 63, iconName: 'tshirt-crew-outline'},
    {id: 64, iconName: 'shoe-heel'},
    {id: 65, iconName: 'tshirt-v'},
    {id: 66, iconName: 'shoe-formal'},
    {id: 67, iconName: 'ring'},
  ],
  Lugares: [
    {id: 68, iconName: 'city'},
    {id: 69, iconName: 'home-group'},
    {id: 70, iconName: 'home-city'},
    {id: 71, iconName: 'home-modern'},
    {id: 73, iconName: 'home'},
  ],
};

export const categories = [
  'Todos',
  'Amor',
  'Automotivos',
  'Animais',
  'Carinhas',
  'Comidas',
  'Espiritualidade',
  'Lugares',
  'Natureza',
  'Objetos',
  'Roupas',
  'Som',
];
