export const colorsGoal = [
  {color: '#d32f2e'},
  {color: '#c2175b'},
  {color: '#7a1fa2'},
  {color: '#512da7'},
  {color: '#303e9f'},
  {color: '#0288d1'},
  {color: '#0098a6'},
  {color: '#00796a'},
  {color: '#398e3d'},
  {color: '#689f39'},
  {color: '#b0b42b'},
  {color: '#fac02e'},
  {color: '#ff9f00'},
  {color: '#f67c01'},
  {color: '#e64a19'},
  {color: '#5d4038'},
  {color: '#465a65'},
  {color: '#616161'},
];

export const iconGoal = [
  {iconName: 'account'},
  {iconName: 'airplane'},
  {iconName: 'anchor'},
  {iconName: 'bike'},
  {iconName: 'boombox'},
  {iconName: 'brightness-5'},
  {iconName: 'bus-side'},
  {iconName: 'cake-variant'},
  {iconName: 'calculator'},
  {iconName: 'city'},
  {iconName: 'compass-outline'},
  {iconName: 'cow'},
  {iconName: 'desktop-mac'},
  {iconName: 'dog-side'},
  {iconName: 'emoticon-excited-outline'},
  {iconName: 'heart'},
  {iconName: 'rocket'},
  {iconName: 'tshirt-crew-outline'},
];
